apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: codewire-docs
  namespace: codewire-prod
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-codewire
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - codewire.sh
      secretName: codewire-tls
  rules:
    - host: codewire.sh
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: codewire-docs
                port:
                  number: 80
