apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: codewire-prod

resources:
  - namespace.yaml
  - registry-secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/name: codewire
      app.kubernetes.io/part-of: codewire
