apiVersion: v1
kind: Service
metadata:
  name: codewire-docs
  namespace: codewire-prod
  labels:
    app.kubernetes.io/name: codewire
    app.kubernetes.io/component: docs
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: codewire
    app.kubernetes.io/component: docs
  ports:
    - port: 80
      targetPort: http
      name: http
