apiVersion: v2
name: codewire-relay
description: A Helm chart for deploying Codewire Relay â€” SSH gateway, device auth, node discovery, and shared KV storage
type: application
version: 0.1.0
appVersion: "0.1.0"
maintainers:
  - name: Sonica
    url: https://codespace.sh
home: https://codewire.sh
sources:
  - https://github.com/codewiresh/codewire
