{{- if eq .Values.relay.authMode "token" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "codewire-relay.fullname" . }}
  labels:
    {{- include "codewire-relay.labels" . | nindent 4 }}
type: Opaque
data:
  auth-token: {{ default (randAlphaNum 32) .Values.relay.authToken | b64enc | quote }}
{{- end }}
