apiVersion: v1
kind: Service
metadata:
  name: {{ include "codewire-relay.fullname" . }}-wg
  labels:
    {{- include "codewire-relay.labels" . | nindent 4 }}
  {{- with .Values.wireguard.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.wireguard.service.type }}
  {{- if and (eq .Values.wireguard.service.type "LoadBalancer") .Values.wireguard.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.wireguard.service.loadBalancerIP }}
  {{- end }}
  ports:
    - port: {{ .Values.relay.wgPort }}
      targetPort: wireguard
      protocol: UDP
      name: wireguard
  selector:
    {{- include "codewire-relay.selectorLabels" . | nindent 4 }}
