apiVersion: v1
kind: Service
metadata:
  name: {{ include "codewire-relay.fullname" . }}-ssh
  labels:
    {{- include "codewire-relay.labels" . | nindent 4 }}
  {{- with .Values.ssh.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.ssh.service.type }}
  {{- if and (eq .Values.ssh.service.type "LoadBalancer") .Values.ssh.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.ssh.service.loadBalancerIP }}
  {{- end }}
  ports:
    - port: 2222
      targetPort: ssh
      protocol: TCP
      name: ssh
  selector:
    {{- include "codewire-relay.selectorLabels" . | nindent 4 }}
