apiVersion: v1
kind: Service
metadata:
  name: demo-broker
  namespace: codewire-demo
spec:
  selector:
    app: demo-broker
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
