apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-broker
  namespace: codewire-demo
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/upstream-hash-by: "$request_uri"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - demo.codewire.sh
    secretName: demo-codewire-tls
  rules:
  - host: demo.codewire.sh
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demo-broker
            port:
              number: 80
